version: "3.9"

services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./src:/code
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres

  db_admin:
    image: adminer
    ports:
      - "8080:8080"
    restart: always
