version: "3.9"

services:
  api_dev:
    build:
      context: .
      dockerfile: Dockerfile_dev
    ports:
      - "5000:5000"
    volumes:
      - ./src:/code
    depends_on:
      - db

  api:
    build:
      context: .
      dockerfile: Dockerfile_prod
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres

  db_admin:
    image: adminer
    ports:
      - "8080:8080"
    restart: always
